/**
 * Arayüz metinleri (Türkçe). Diğer diller (en, ar, ru, de) aynı yapıyla eklenir;
 * `yon: 'rtl'` Arapça için sayfa yönünü çevirir.
 */
export const tr = {
  dil: 'tr',
  yon: 'ltr' as 'ltr' | 'rtl',
  uygulama: {
    ad: 'DC Doktor Klinik',
    aciklama: 'Klinik, poliklinik, diş, estetik, veteriner ve evde sağlık kuruluşları için yönetim platformu',
  },
  genel: {
    devam: 'Devam',
    geri: 'Geri',
    vazgec: 'Vazgeç',
    kaydet: 'Kaydet',
    duzenle: 'Düzenle',
    yukleniyor: 'Yükleniyor…',
    beklenmeyenHata: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
    baglantiHatasi: 'Sunucuya ulaşılamadı. İnternet bağlantınızı kontrol edin.',
    yakinda: 'Yakında',
    tumSubeler: 'Tüm şubeler',
  },
  giris: {
    baslik: 'Giriş yapın',
    altBaslik: 'Kurumunuzun hesabıyla oturum açın.',
    eposta: 'E-posta',
    parola: 'Parola',
    dugme: 'Giriş yap',
    hesabinYokMu: 'Kurumunuz henüz kayıtlı değil mi?',
    kayitOl: 'Kurum kaydı oluşturun',
  },
  kayit: {
    adimlar: ['Kurum tipi', 'Kurum bilgileri', 'Hesabınız', 'Onay'],
    adim: (n: number, toplam: number) => `Adım ${n} / ${toplam}`,
    tip: {
      baslik: 'Kurumunuz hangi hizmetleri veriyor?',
      aciklama:
        'Birden fazla seçebilirsiniz. Seçiminize göre modüller, roller, formlar, zorunlu belgeler ve resmî bağlantılar otomatik hazırlanır. Sonradan şube bazında değiştirilebilir.',
      ozetBaslik: 'Kurumunuz için hazırlanacaklar',
      ozetAlt: 'Seçim değiştikçe güncellenir',
      moduller: 'Modüller',
      roller: 'Roller ve varsayılan yetkiler',
      belgeler: 'Takip edilecek zorunlu belgeler',
      entegrasyonlar: 'Resmî bağlantılar',
      bosSecim: 'Başlamak için en az bir kurum tipi seçin',
      ayriSube:
        'Veteriner hizmeti ile insan sağlığı hizmetleri farklı bakanlıkların mevzuatına tabidir. Bu seçimde sistem her birini ayrı şube olarak açar; hasta ve hayvan kayıtları birbirine karışmaz.',
      secildi: (n: number) => `${n} kurum tipi seçildi`,
    },
    kurum: {
      baslik: 'Kurum bilgileri',
      aciklama: 'Resmî unvan faturalarda ve belgelerde kullanılır.',
      unvan: 'Resmî unvan',
      unvanIpucu: 'Ör. Örnek Sağlık Hizmetleri Ltd. Şti.',
      vergiNo: 'Vergi no veya T.C. kimlik no (isteğe bağlı)',
      subeAdi: 'İlk şubenin adı',
      subeIpucu: 'Ör. Merkez, Kadıköy',
    },
    hesap: {
      baslik: 'Hesabınız',
      aciklama: 'Bu hesap kurumun sahibi olarak açılır. Diğer çalışanları kayıttan sonra davet edersiniz.',
      adSoyad: 'Ad soyad',
      eposta: 'E-posta',
      parola: 'Parola',
      parolaIpucu: 'En az 10 karakter',
      parolaTekrar: 'Parola (tekrar)',
      parolaUyusmuyor: 'Parolalar aynı değil.',
      meslek: 'Mesleğiniz',
      hekimBilgi:
        'Hekim olduğunuz için kurumun mesul müdürü ve hekimi olarak da atanacaksınız. Mesul müdürlüğü sonradan başka bir hekime devredebilirsiniz.',
      idariBilgi:
        'Hekim olmadığınız için hastaların tıbbi kayıtlarını göremezsiniz; işletme verilerini ve anonim istatistikleri görürsünüz. Kayıttan sonra bir hekimi mesul müdür olarak atamanız gerekir.',
    },
    onay: {
      baslik: 'Bilgileri kontrol edin',
      kurumTipleri: 'Kurum tipleri',
      subeler: 'Açılacak şubeler',
      sahip: 'Kurum sahibi',
      kosullar: 'Kullanım koşullarını ve kişisel verilerin işlenmesine ilişkin aydınlatma metnini okudum.',
      kosullarNot: 'Metinler taslaktır; hukuki onay sonrası yayınlanacaktır.',
      dugme: 'Kurumu oluştur',
    },
  },
  panel: {
    menu: {
      komuta: 'Komuta Merkezi',
      randevular: 'Randevular',
      hastalar: 'Hastalar',
      klinik: 'Klinik',
      personel: 'Personel ve Belgeler',
      nobet: 'Nöbet ve Vardiya',
      stok: 'Stok ve Cihaz',
      finans: 'Finans',
      kalite: 'Kalite ve Uyum',
      raporlar: 'Raporlar',
      kullanicilar: 'Kullanıcılar ve Yetkiler',
      denetim: 'Denetim İzi',
      belgeler: 'Ruhsat ve Belgeler',
      anaMenu: 'Ana menü',
    },
    sube: 'Şube',
    cikis: 'Çıkış yap',
    komuta: {
      baslik: 'Komuta Merkezi',
      hosgeldin: (ad: string) => `Hoş geldiniz, ${ad}`,
      skor: 'Kurum Sağlık Skoru',
      skorBos: 'Randevu, finans ve personel verileri biriktikçe hesaplanır.',
      kurulum: 'Kurulum adımları',
      kurulumAlt: 'Kurumunuzu kullanıma hazırlamak için',
      adimMesul: 'Mesul müdür ata',
      adimMesulTamam: 'Mesul müdür atandı',
      adimEkip: 'Ekibinizi davet edin',
      adimFiyat: 'Hizmet ve fiyat listesini oluşturun',
      adimBelge: 'Ruhsat ve zorunlu belgeleri yükleyin',
      kartlar: {
        randevu: 'Bugünkü randevular',
        ciro: 'Bugünkü ciro',
        alacak: 'Tahsil edilmemiş alacak',
        bekleme: 'Ortalama bekleme',
        veriYok: 'Henüz veri yok',
        randevuAlt: (gelen: number, salonda: number, gelmedi: number) => `${gelen} geldi · ${salonda} salonda · ${gelmedi} gelmedi`,
        ciroAlt: 'Net tahsilat (iadeler düşülmüş)',
        alacakAlt: (n: number) => `${n} hastada açık bakiye`,
        beklemeAlt: 'Geliş → muayeneye alınma',
        dakika: (n: number) => `${n} dk`,
      },
      ciroGrafik: 'Son 14 gün net tahsilat',
      ciroGrafikAlt: 'Bugün mercan renkte',
      ciroYok: 'Son 14 günde tahsilat yok.',
      tabloGoster: 'Tablo olarak göster',
      gun: 'Gün',
      tutar: 'Net tahsilat',
      tumSubelerNotu: 'Tüm şubelerin toplamı gösteriliyor.',
      yetkisiz: 'Rolünüze ait çalışma ekranları sonraki geliştirme adımlarında açılacak.',
      rolleriniz: 'Rolleriniz',
    },
    kullanicilar: {
      baslik: 'Kullanıcılar ve Yetkiler',
      aciklama: 'Çalışanları ekleyin ve rollerini atayın. Sağlık rollerini mesul müdür onaylar; kimse kendine rol veremez.',
      ekle: 'Kullanıcı ekle',
      eposta: 'E-posta',
      adSoyad: 'Ad soyad',
      meslek: 'Meslek',
      geciciParola: 'Geçici parola',
      geciciParolaIpucu: 'Kişiye güvenli bir yoldan iletin. E-posta ile davet sonraki adımda eklenecek.',
      eklendi: 'Kullanıcı eklendi. Şimdi rolünü atayın.',
      roller: 'Roller',
      rolYok: 'Rol atanmamış',
      rolAta: 'Rol ata',
      rol: 'Rol',
      kapsam: 'Geçerli olduğu yer',
      atandi: 'Rol atandı.',
      kendin: '(siz)',
      rolGerekceleri: {
        'mesul.mudur.ata': 'Mesul müdürü yalnızca kurum sahibi atayabilir.',
        'yetki.saglik.onayla': 'Sağlık rollerini (hekim, hemşire vb.) mesul müdür atar.',
        'kullanici.yonet': 'Bu rolü atamak için kullanıcı yönetimi yetkisi gerekir.',
      } as Record<string, string>,
    },
    denetim: {
      baslik: 'Denetim İzi',
      aciklama: 'Kurumunuzdaki girişler, yetki değişiklikleri ve reddedilen erişimler. Kayıtlar değiştirilemez ve silinemez.',
      zaman: 'Zaman',
      eylem: 'Eylem',
      kullanici: 'Kullanıcı',
      ayrinti: 'Ayrıntı',
      ip: 'IP',
      bos: 'Henüz kayıt yok.',
      eylemler: {
        'kurum.kayit': 'Kurum kaydı oluşturuldu',
        'giris.basarili': 'Giriş yapıldı',
        'giris.basarisiz': 'Başarısız giriş denemesi',
        'kullanici.olusturuldu': 'Kullanıcı eklendi',
        'rol.atandi': 'Rol atandı',
        'rol.atama.reddedildi': 'Rol ataması reddedildi',
        'erisim.reddedildi': 'Yetkisiz erişim denemesi',
        'hasta.olusturuldu': 'Hasta kaydedildi',
        'hasta.goruntulendi': 'Hasta kartı görüntülendi',
        'hasta.arandi': 'Hasta araması yapıldı',
        'hasta.guncellendi': 'Hasta bilgileri güncellendi',
        'hasta.kimlik.goruntulendi': 'Açık kimlik no görüntülendi',
        'hasta.uyari.eklendi': 'Hasta uyarısı eklendi',
        'hasta.uyari.kaldirildi': 'Hasta uyarısı kaldırıldı',
        'riza.verildi': 'Açık rıza verildi',
        'riza.geri.cekildi': 'Açık rıza geri çekildi',
        'hayvan.olusturuldu': 'Hayvan kaydedildi',
        'randevu.olusturuldu': 'Randevu verildi',
        'randevu.durum': 'Randevu durumu değişti',
        'randevu.tasindi': 'Randevu taşındı',
        'kaynak.olusturuldu': 'Oda / cihaz eklendi',
        'muayene.acildi': 'Muayene kaydı açıldı',
        'muayene.goruntulendi': 'Muayene kaydı görüntülendi',
        'muayene.guncellendi': 'Muayene kaydı güncellendi',
        'muayene.imzalandi': 'Muayene kaydı imzalandı',
        'muayene.imza.reddedildi': 'İmza reddedildi (parola)',
        'muayene.ek.not': 'Muayeneye ek not eklendi',
        'muayene.listelendi': 'Muayene geçmişi görüntülendi',
        'acil.erisim': 'ACİL ERİŞİM açıldı',
        'hizmet.olusturuldu': 'Hizmet eklendi',
        'fiyat.degisti': 'Fiyat değiştirildi',
        'fiyat.talep': 'Fiyat onaya gönderildi',
        'fiyat.onaylandi': 'Fiyat onaylandı',
        'fiyat.reddedildi': 'Fiyat talebi reddedildi',
        'hesap.kalem': 'Hesaba hizmet eklendi',
        'hesap.kalem.iptal': 'Hesap kalemi iptal edildi',
        'tahsilat': 'Tahsilat alındı',
        'iade': 'İade yapıldı',
        'kasa.kapandi': 'Kasa kapatıldı',
        'kasa.kapandi.farkli': 'Kasa FARKLI kapatıldı',
        'belge.eklendi': 'Belge eklendi',
        'belge.kaldirildi': 'Belge kaldırıldı',
        'belge.dosya.indirildi': 'Belge dosyası indirildi',
        'personel.goruntulendi': 'Personel kartı görüntülendi',
        'personel.guncellendi': 'Personel bilgileri güncellendi',
        'cizelge.olusturuldu': 'Nöbet çizelgesi oluşturuldu',
        'gorev.eklendi': 'Çizelgeye görev eklendi',
        'gorev.silindi': 'Çizelgeden görev silindi',
        'cizelge.onaya.gonderildi': 'Çizelge onaya gönderildi',
        'cizelge.onaylandi': 'Çizelge onaylandı ve yayınlandı',
        'cizelge.ihlalle.onaylandi': 'Çizelge KURAL İHLALİYLE onaylandı',
        'cizelge.reddedildi': 'Çizelge reddedildi',
        'cizelge.revizyon': 'Çizelge taslağa alındı',
        'cizelge.karar.reddedildi': 'Çizelge onayı reddedildi (kendi çizelgesi)',
        'nobet.ayar': 'Nöbet kuralları değişti',
        'izin.eklendi': 'Personel izni eklendi',
        'izin.iptal': 'Personel izni iptal edildi',
      } as Record<string, string>,
    },
  },
  hastalar: {
    baslik: 'Hastalar',
    aciklama: 'Hasta kaydı işletme genelinde tektir; hasta hangi şubeye gelirse gelsin aynı kart kullanılır.',
    ara: 'Hasta ara',
    araIpucu: 'Ad soyad, telefon veya T.C. kimlik no',
    yeni: 'Yeni hasta',
    sonKayitlar: 'Son kaydedilen hastalar',
    sonucYok: 'Aramanıza uyan hasta bulunamadı.',
    sutun: { adSoyad: 'Ad soyad', dogum: 'Doğum tarihi', kimlik: 'Kimlik', telefon: 'Telefon' },
    yas: (y: number) => `${y} yaş`,
    form: {
      baslik: 'Yeni hasta kaydı',
      kimlikBolum: 'Kimlik',
      kimlikTuru: 'Kimlik türü',
      kimlikNo: 'Kimlik / pasaport no',
      kisiselBolum: 'Kişisel bilgiler',
      ad: 'Ad',
      soyad: 'Soyad',
      dogumTarihi: 'Doğum tarihi',
      cinsiyet: 'Cinsiyet',
      uyruk: 'Uyruk',
      kanGrubu: 'Kan grubu',
      iletisimBolum: 'İletişim',
      telefon: 'Cep telefonu',
      eposta: 'E-posta',
      adres: 'Adres',
      iletisimTercihi: 'Tercih ettiği iletişim kanalı',
      acilBolum: 'Acil durumda aranacak kişi',
      temsilciBolum: 'Veli / vasi / yasal temsilci',
      temsilciIpucu: '18 yaşından küçük veya kısıtlı hastalarda onamları yasal temsilci verir.',
      kisiAd: 'Ad soyad',
      kisiTelefon: 'Telefon',
      yakinlik: 'Yakınlık',
      kvkkBolum: 'KVKK — aydınlatma ve açık rıza',
      aydinlatmaSunuldu: 'Kişisel verilerin işlenmesine ilişkin aydınlatma metni hastaya sunuldu.',
      aydinlatmaKanali: 'Sunulduğu yöntem',
      aydinlatmaNot: 'Aydınlatma sunulmadan kayıt tamamlanamaz. Metin taslaktır; hukuki onay sonrası güncellenecektir.',
      rizaBaslik: 'Açık rızalar (her biri ayrı; vermemek hizmet almayı engellemez)',
      kaydet: 'Hastayı kaydet',
      zatenKayitli: 'Bu kimlik numarasıyla kayıtlı bir hasta var.',
      mevcutKaydaGit: 'Mevcut kaydı aç',
      benzerBaslik: 'Benzer bilgilere sahip kayıtlı hasta var. Aynı kişi olabilir mi?',
      buHasta: 'Bu hasta',
      yinedeKaydet: 'Farklı kişi — yine de yeni kayıt oluştur',
      secin: '—',
    },
    kart: {
      goster: 'Göster',
      gizle: 'Gizle',
      gosterIpucu: 'Açık kimlik numarasının görüntülenmesi kayda alınır.',
      kisisel: 'Kişisel ve iletişim bilgileri',
      acil: 'Acil durum kişisi',
      temsilci: 'Yasal temsilci',
      yok: 'Belirtilmemiş',
      uyarilar: 'Uyarılar',
      uyariYok: 'Görüntüleyebileceğiniz uyarı yok.',
      uyariEkle: 'Uyarı ekle',
      uyariTuru: 'Uyarı türü',
      uyariAciklama: 'Açıklama',
      kaldir: 'Kaldır',
      kvkk: 'KVKK',
      aydinlatma: (surum: string, tarih: string) => `Aydınlatma metni (${surum}) ${tarih} tarihinde sunuldu.`,
      aydinlatmaYok: 'Aydınlatma kaydı yok.',
      rizaVerildi: 'Rıza verildi',
      rizaYok: 'Rıza yok',
      rizaVer: 'Rıza kaydet',
      rizaGeriCek: 'Geri çek',
      rizaKanal: 'Yöntem',
      hayvanlar: 'Hayvanları',
      hayvanYok: 'Kayıtlı hayvan yok.',
      hayvanEkle: 'Hayvan ekle',
      hayvanAd: 'Adı',
      hayvanTur: 'Türü',
      irk: 'Irkı',
      hayvanCinsiyet: 'Cinsiyeti',
      kisirlastirilmis: 'Kısırlaştırılmış',
      mikrocip: 'Mikroçip no (15 hane)',
      dogumTarihi: 'Doğum tarihi',
      kaydedildi: 'Kaydedildi.',
    },
  },
  randevular: {
    baslik: 'Randevular',
    subeSecin: 'Randevular şube bazında tutulur. Devam etmek için bir şube seçin.',
    bugun: 'Bugün',
    oncekiGun: 'Önceki gün',
    sonrakiGun: 'Sonraki gün',
    yeni: 'Yeni randevu',
    ozet: (toplam: number, bos: number) => `${toplam} randevu · ${bos} hekim`,
    hekimYok: 'Bu şubede takvimi olan sağlık personeli yok. Kullanıcılar ve Yetkiler’den hekim ekleyin.',
    bosAlanIpucu: 'Boş bir saate tıklayarak randevu verebilirsiniz.',
    simdi: 'Şimdi',
    bekleme: 'Bekleme salonu',
    beklemeBos: 'Salonda bekleyen hasta yok.',
    beklemeSuresi: (dk: number) => `${dk} dk`,
    siraNo: 'Sıra',
    ayrinti: 'Randevu',
    kapat: 'Kapat',
    hastaKarti: 'Hasta kartını aç',
    saat: 'Saat',
    hekim: 'Hekim',
    kaynak: 'Oda / cihaz',
    kaynakYok: 'Oda / cihaz seçilmedi',
    tur: 'Randevu türü',
    not: 'Not',
    sure: 'Süre',
    dakika: (d: number) => `${d} dk`,
    islemler: {
      geldi: 'Hasta geldi (kabul)',
      muayenede: 'Muayeneye al',
      tamamlandi: 'Tamamla',
      gelmedi: 'Gelmedi',
      iptal: 'İptal et',
    } as Record<string, string>,
    iptalNedeni: 'İptal nedeni',
    iptalOnayla: 'İptali onayla',
    form: {
      baslik: 'Yeni randevu',
      hasta: 'Hasta',
      hastaAra: 'Ad, telefon veya kimlik no ile arayın',
      hastaDegistir: 'Değiştir',
      yeniHasta: 'Kayıtlı değil mi? Yeni hasta kaydı',
      hayvan: 'Hayvan',
      hayvanYok: 'Bu kişinin kayıtlı hayvanı yok; hasta kartından ekleyin.',
      kaydet: 'Randevuyu kaydet',
    },
    kaynakYonetimi: 'Odalar ve cihazlar',
    kaynakEkle: 'Ekle',
    kaynakAd: 'Adı',
    kaynakTur: 'Türü',
  },
  muayene: {
    baslik: 'Muayene',
    ac: 'Muayene kaydını aç',
    erisimNotu: (neden: string) => `Erişiminiz kayda alınıyor · ${neden}`,
    erisimNedenleri: { tedavi: 'Tedavi ilişkisi', randevu: 'Bugünkü randevu', denetim: 'Kurumsal denetim', acil: 'Acil erişim (süreli)' } as Record<string, string>,
    oncekiler: 'Önceki muayeneler',
    oncekiYok: 'Önceki muayene yok.',
    sikayet: 'Şikâyet',
    vitaller: 'Vital bulgular',
    vitalNot: (ad: string, saat: string) => `Son giriş: ${ad ? `${ad} · ` : ''}${saat}`,
    vki: 'VKİ',
    olaganDisi: 'Olağan dışı',
    fizik: 'Fizik muayene',
    tanilar: 'Tanılar (ICD-10)',
    taniAra: 'Tanı adı veya ICD-10 kodu ile arayın',
    taniKural: 'Tanı girilmeden reçete yazılamaz ve kayıt imzalanamaz.',
    birincil: 'Birincil',
    kaldir: 'Kaldır',
    plan: 'Plan ve öneriler',
    kontrol: 'Kontrol tarihi',
    recete: 'e-Reçete taslağı',
    receteNot: 'e-Reçete sistemine gönderim, entegrasyon tamamlandığında imzayla birlikte yapılacak.',
    ilac: 'İlaç (ad ve form)',
    doz: 'Doz',
    kullanim: 'Kullanım',
    sureGun: 'Süre (gün)',
    kutu: 'Kutu',
    ilacEkle: 'İlaç ekle',
    kararDestegi: 'Klinik karar desteği',
    alerjiUyari: (a: string) => `Alerji: ${a} — reçeteyi bu alerjiye göre kontrol edin.`,
    alerjiEslesme: (ilac: string, a: string) => `“${ilac}” reçetede; hastanın “${a}” alerjisi kayıtlı.`,
    vitalUyari: (ad: string, d: string) => `${ad} olağan aralığın dışında: ${d}`,
    uyariYok: 'Dikkat gerektiren bulgu yok.',
    kararNot: 'Basit kural kontrolleridir; klinik karar hekime aittir. İlaç etkileşim veritabanı entegrasyonu sonraki adımdadır.',
    kaydediliyor: 'Kaydediliyor…',
    kaydedildi: (saat: string) => `Taslak kaydedildi · ${saat}`,
    imzala: 'İmzala ve bitir',
    imzaBaslik: 'Kaydı imzala',
    imzaAciklama: 'İmzalanan kayıt değiştirilemez; sonradan yalnızca ek not eklenebilir. Onaylamak için parolanızı girin.',
    parola: 'Parolanız',
    imzaOnay: 'İmzala',
    imzali: (tarih: string, ozet: string) => `İmzalandı · ${tarih} · Özet ${ozet}`,
    saltOkunur: 'Bu kaydı düzenleme yetkiniz yok; yalnızca görüntülüyorsunuz.',
    ekNotlar: 'Ek notlar',
    ekNotEkle: 'Ek not ekle',
    ekNot: 'Not',
    gecmis: 'Muayene geçmişi',
    gecmisYok: 'Muayene kaydı yok.',
    tedaviIliskisiYok: 'Bu hastayla tedavi ilişkiniz yok; tıbbi kaydı görmek için gerekçeli acil erişim açabilirsiniz. Erişim 4 saat geçerlidir ve denetim izine işaretli olarak yazılır.',
    acilErisim: 'Acil erişim aç',
    gerekce: 'Gerekçe',
    gerekceAciklama: 'Açıklama (en az 10 karakter)',
    gerekceler: { acil_mudahale: 'Acil müdahale', konsultasyon: 'Konsültasyon', nobet_devri: 'Nöbet / hasta devri' } as Record<string, string>,
  },
  finans: {
    baslik: 'Finans',
    aciklama: 'Gün sonu kasa, hizmetler ve fiyatlar. Fiyat değişiklikleri kurum sahibinin onayıyla geçerli olur.',
    kasa: 'Gün sonu kasa',
    subeSecin: 'Kasa şube bazında tutulur; bir şube seçin.',
    gun: 'Gün',
    odemeTuru: 'Ödeme türü',
    tahsilat: 'Tahsilat',
    iade: 'İade',
    net: 'Net',
    toplam: 'Toplam',
    hareketler: 'Hareketler',
    hareketYok: 'Bu gün için hareket yok.',
    beklenenNakit: 'Kasada olması gereken nakit',
    sayilanNakit: 'Sayılan nakit (TL)',
    farkAciklama: 'Fark açıklaması',
    kapat: 'Kasayı kapat',
    kapandi: (kim: string, fark: string) => `Kasa kapatıldı · ${kim} · fark ${fark}`,
    hizmetler: 'Hizmetler ve fiyatlar',
    hizmetYok: 'Henüz hizmet yok. Hasta hesabına eklemek için önce hizmet tanımlayın.',
    kod: 'Kod',
    ad: 'Hizmet adı',
    kategori: 'Kategori',
    kdv: 'KDV %',
    fiyat: 'Fiyat (KDV dahil, TL)',
    hizmetEkle: 'Hizmet ekle',
    fiyatDegistir: 'Fiyatı değiştir',
    yeniFiyat: 'Yeni fiyat (TL)',
    onayBekliyor: 'Onay bekliyor',
    pasif: 'Pasif',
    talepGonderildi: 'Fiyat onaya gönderildi.',
    uygulandi: 'Fiyat güncellendi.',
    talepler: 'Onay bekleyen fiyatlar',
    talepYok: 'Onay bekleyen fiyat yok.',
    onayla: 'Onayla',
    reddet: 'Reddet',
    kendiTalebin: 'Kendi talebiniz — başka bir yetkili onaylamalı',
    iadeYap: 'İade',
    iadeTutari: 'İade tutarı (TL)',
    iadeNedeni: 'İade nedeni',
    hesap: 'Hesap',
    borc: 'Hizmet toplamı',
    odenen: 'Ödenen',
    bakiye: 'Bakiye',
    avans: 'Avans (fazla ödeme)',
    kalemEkle: 'Hizmet ekle',
    hizmet: 'Hizmet',
    adet: 'Adet',
    indirim: 'İndirim %',
    indirimNedeni: 'İndirim nedeni',
    indirimNot: (e: number) => `%${e} üzerindeki indirimi yalnızca yönetici uygulayabilir.`,
    tahsilatAl: 'Tahsilat al',
    tutar: 'Tutar (TL)',
    aciklamaAlan: 'Açıklama',
    kalemler: 'Hizmetler',
    tahsilatlar: 'Ödemeler',
    iptal: 'İptal et',
    iptalNedeni: 'İptal nedeni',
    iptalEdildi: 'İptal edildi',
    faturaNot: 'e-Arşiv / e-Fatura kesimi özel entegratör bağlantısıyla eklenecek.',
  },
  belge: {
    durum: {
      dolmus: (g: number) => `Süresi doldu (${g} gün önce)`,
      bugun: 'Bugün doluyor',
      kalan: (g: number) => `${g} gün kaldı`,
      gecerli: 'Geçerli',
      suresiz: 'Süresiz',
      eksik: 'Eksik',
    },
    tur: 'Belge türü',
    belgeNo: 'Belge / poliçe no',
    verenKurum: 'Veren kurum',
    baslangic: 'Başlangıç',
    bitis: 'Bitiş tarihi',
    bitisZorunlu: 'Bu belge süreli; bitiş tarihi zorunlu.',
    aciklama: 'Not',
    dosya: 'Dosya (PDF, JPEG, PNG · en çok 10 MB)',
    ekle: 'Belge ekle',
    eklendi: 'Belge eklendi.',
    indir: 'İndir',
    kaldir: 'Kaldır',
    kaldirNedeni: 'Kaldırma nedeni',
    kaldirildi: (neden: string) => `Kaldırıldı · ${neden}`,
    eskiSurum: 'Önceki sürüm',
    gecmis: (n: number) => `Geçmiş ve kaldırılan belgeler (${n})`,
    eksikler: 'Eksik zorunlu belgeler',
    eksikYok: 'Zorunlu belgelerin tamamı yüklü.',
    ekleyen: 'Ekleyen',
    kendiEkledi: 'kişinin kendisi ekledi',
    dosyaYok: 'Dosya yok',
    belgeYok: 'Henüz belge yok.',
    askiUyari: (belge: string, tarih: string) => `${belge} ${tarih} tarihinde doldu. Tanı, reçete, rapor, onam ve tıbbi kayda giriş askıya alındı; görüntüleme açık.`,
    askiUyariKendi: (belge: string, tarih: string) => `${belge} süreniz ${tarih} tarihinde doldu. Tanı, reçete, rapor ve tıbbi kayda giriş işlemleriniz askıya alındı. Yenilenmiş belgeyi personel birimine iletin.`,
    askiDetay: 'Belgelerim',
  },
  personel: {
    baslik: 'Personel',
    aciklama: 'Çalışanların özlük bilgileri ve süreli belgeleri. Süresi dolan zorunlu belge ilgili işlemleri otomatik askıya alır.',
    adSoyad: 'Ad soyad',
    meslek: 'Meslek / unvan',
    roller: 'Roller',
    belgeler: 'Belgeler',
    sorunlular: 'Yalnızca dikkat gerekenler',
    askida: 'İşlem askıda',
    dolmus: (n: number) => `${n} dolmuş`,
    ozet: (d: number, k: number, e: number) => `${d} dolmuş · ${k} yaklaşan · ${e} eksik`,
    hepsiTamam: 'Belgeler tamam',
    ozluk: 'Özlük bilgileri',
    unvanBrans: 'Unvan / branş',
    calismaSekli: 'Çalışma şekli',
    iseGiris: 'İşe giriş',
    telefon: 'Cep telefonu',
    kaydedildi: 'Özlük bilgileri kaydedildi.',
    eposta: 'E-posta',
    geri: '← Personel',
    kendiKartim: 'Belgelerim',
  },
  nobet: {
    baslik: 'Nöbet ve Vardiya',
    aciklama: 'Aylık çizelge: planlayıcı hazırlar, başka bir yetkili onaylayıp yayınlar. Çakışan görev ve izinli güne görev verilemez.',
    subeSecin: 'Çizelge şube bazında tutulur; bir şube seçin.',
    oncekiAy: 'Önceki ay',
    sonrakiAy: 'Sonraki ay',
    olustur: 'Bu ay için çizelge oluştur',
    yok: 'Bu ay için yayında çizelge yok.',
    taslakGizli: 'Çizelge hazırlanıyor; yayınlandığında burada görünecek.',
    personel: 'Personel',
    izin: 'İzin',
    hucre: (kisi: string, gun: string) => `${kisi}, ${gun}`,
    secili: 'Seçili gün',
    sablonlar: 'Hızlı ekle',
    ozel: 'Özel saat',
    tur: 'Görev türü',
    baslangic: 'Başlangıç saati',
    sure: 'Süre (saat)',
    ekle: 'Ekle',
    kaldir: 'Kaldır',
    kapat: 'Kapat',
    gorevYok: 'Bu gün görev yok.',
    ihlaller: 'Kural ihlalleri',
    ihlalYok: 'Kural ihlali yok.',
    onayaGonder: 'Onaya gönder',
    onayla: 'Onayla ve yayınla',
    reddet: 'Reddet',
    redNedeni: 'Red nedeni',
    gerekce: 'İhlal gerekçesi (zorunlu)',
    gerekceIpucu: 'Kural dışı çizelgeyi neden onayladığınızı yazın; denetim izine kaydedilir.',
    revizyon: 'Değişiklik için taslağa al',
    kendiGonderdin: 'Onaya siz gönderdiniz; başka bir yetkili onaylamalı.',
    hazirlayan: 'Hazırlayan',
    onaylayan: (kim: string, zaman: string) => `Onaylayan: ${kim} · ${zaman}`,
    reddedildi: (neden: string) => `Reddedildi: ${neden}`,
    ihlalGerekcesi: (g: string) => `İhlal gerekçesi: ${g}`,
    ayarlar: 'Kurallar',
    ayarMetni: (h: number, d: number, g: number) => `Haftada en çok ${h} saat · nöbet sonrası en az ${d} saat dinlenme · en çok ${g} gece üst üste`,
    haftalik: 'Haftalık azami saat',
    dinlenme: 'Nöbet sonrası dinlenme (saat)',
    gece: 'Üst üste azami gece',
    ayarKaydedildi: 'Kurallar güncellendi.',
    gorevlerim: 'Görevlerim (30 gün)',
    gorevlerimBos: 'Yayındaki çizelgede önümüzdeki 30 gün için göreviniz yok.',
    toplamSaat: (n: number) => `${n} sa`,
  },
  izinler: {
    baslik: 'İzinler',
    tur: 'İzin türü',
    baslangic: 'Başlangıç',
    bitis: 'Bitiş',
    aciklama: 'Açıklama',
    ekle: 'İzin ekle',
    yok: 'Kayıtlı izin yok.',
    iptal: 'İptal et',
    iptalEdildi: 'İptal edildi',
  },
  kurumBelgeleri: {
    baslik: 'Ruhsat ve Belgeler',
    aciklama: 'Kurum ruhsatları, sözleşmeler ve lisanslar. Süresi yaklaşan belgeler 120, 60 ve 30 gün kala uyarı verir.',
    isletmeGeneli: 'Tüm işletme için geçerli',
    sube: 'Şube',
    tumIsletme: 'Tüm işletme',
  },
  alarmlar: {
    baslik: 'Yapılacaklar ve alarmlar',
    bos: 'Açık alarm yok.',
    seviye: { kritik: 'Kritik', ciddi: 'Yakın', uyari: 'Uyarı', eksik: 'Eksik' },
    eksikBelge: (tur: string) => `${tur} yüklenmemiş`,
    eksikBelgeler: (n: number, liste: string) => `${n} zorunlu belge yüklenmemiş: ${liste}`,
    cizelgeYok: (ay: string, g: number) => `${ay} nöbet çizelgesi yayında değil (${g} gün kaldı)`,
    cizelgeOnay: (ay: string) => `${ay} nöbet çizelgesi onayınızı bekliyor`,
    dolmus: (tur: string, g: number) => `${tur} ${g} gün önce doldu`,
    yaklasan: (tur: string, g: number) => (g === 0 ? `${tur} bugün doluyor` : `${tur} ${g} gün sonra doluyor`),
    askida: 'işlemler askıda',
    tumu: (n: number) => `Tümünü göster (${n})`,
    daha: 'Daha az göster',
  },
  hatalar: {
    GIRIS_BASARISIZ: 'E-posta veya parola hatalı.',
    EPOSTA_KULLANIMDA: 'Bu e-posta adresiyle kayıtlı bir kullanıcı var.',
    KIMLIK_GEREKLI: 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.',
    YETKI_YOK: 'Bu işlem için yetkiniz yok.',
    MESLEK_UYGUN_DEGIL: 'Bu rol, kişinin mesleğine atanamaz.',
    KENDI_YETKISI: 'Kendinize rol atayamazsınız; başka bir yetkili atamalıdır.',
    ROL_ZATEN_ATANMIS: 'Bu rol bu kapsamda zaten atanmış.',
    SUBE_BULUNAMADI: 'Şube bulunamadı.',
    GECERSIZ_ISTEK: 'Bazı alanlar geçersiz.',
    HASTA_BULUNAMADI: 'Hasta bulunamadı.',
    HASTA_ZATEN_KAYITLI: 'Bu kimlik numarasıyla kayıtlı bir hasta var.',
    BENZER_KAYIT_VAR: 'Benzer bilgilere sahip kayıtlı hasta var.',
    VETERINER_SUBE_YOK: 'Hayvan kaydı için kurumda veteriner şubesi bulunmalı.',
    HEKIM_DOLU: 'Hekimin bu saatte başka bir randevusu var.',
    KAYNAK_DOLU: 'Oda / cihaz bu saatte başka bir randevuda kullanılıyor.',
    SUBE_SECILMELI: 'Randevu işlemleri için bir şube seçin.',
    GECERSIZ_DURUM_GECISI: 'Randevu bu duruma geçirilemez.',
    HEKIM_UYGUN_DEGIL: 'Seçilen kişiye bu şubede randevu verilemez.',
    HAYVAN_GEREKLI: 'Veteriner şubesinde randevu bir hayvan için verilir.',
    TASINAMAZ: 'Yalnızca henüz gelinmemiş randevular taşınabilir.',
    KAYNAK_ADI_KULLANIMDA: 'Bu şubede aynı adlı bir oda / cihaz var.',
    RANDEVU_BULUNAMADI: 'Randevu bulunamadı.',
    TEDAVI_ILISKISI_YOK: 'Bu hastayla tedavi ilişkiniz yok.',
    HASTA_GELMEDI: 'Muayene kaydı, hasta kabul edildikten sonra açılır.',
    TANI_GEREKLI: 'Önce tanı girin.',
    MUAYENE_IMZALI: 'İmzalanmış kayıt değiştirilemez; ek not ekleyin.',
    KAYDIN_HEKIMI_DEGIL: 'Bu işlemi yalnızca muayeneyi yapan hekim yapabilir.',
    PAROLA_HATALI: 'Parola hatalı; kayıt imzalanmadı.',
    MUAYENE_BULUNAMADI: 'Muayene kaydı bulunamadı.',
    HIZMET_ONAYSIZ: 'Hizmetin fiyatı henüz onaylanmadı.',
    HIZMET_KODU_KULLANIMDA: 'Bu kodla bir hizmet var.',
    BEKLEYEN_TALEP_VAR: 'Bu hizmet için onay bekleyen bir fiyat talebi var.',
    KENDI_TALEBI: 'Kendi talebinizi onaylayamazsınız.',
    INDIRIM_ONAY_GEREKLI: 'Bu orandaki indirimi yalnızca yetkili yönetici uygulayabilir.',
    GOREVLER_AYRILIGI: 'Tahsilatı alan kişi iadesini yapamaz; başka bir yetkili yapmalıdır.',
    IADE_TUTARI_ASIMI: 'İade toplamı tahsil edilen tutarı aşamaz.',
    KASA_KAPALI: 'Bugünün kasası kapatıldı; yeni hareket girilemez.',
    KASA_ZATEN_KAPALI: 'Bu günün kasası zaten kapatılmış.',
    FARK_ACIKLAMASI_GEREKLI: 'Kasada fark var; açıklama yazın.',
    MIKROCIP_KAYITLI: 'Bu mikroçip numarasıyla kayıtlı bir hayvan var.',
    BELGE_SURESI_DOLDU: 'Zorunlu belgenizin süresi dolduğu için bu işlem askıya alındı. Yenilenmiş belgeyi personel birimine iletin.',
    DOSYA_TURU: 'Yalnızca PDF, JPEG veya PNG dosyası yüklenebilir.',
    DOSYA_BUYUK: 'Dosya en çok 10 MB olabilir.',
    PERSONEL_BULUNAMADI: 'Personel bulunamadı.',
    BELGE_BULUNAMADI: 'Belge bulunamadı.',
    BELGE_KALDIRILMIS: 'Belge zaten kaldırılmış.',
    DOSYA_YOK: 'Bu belgeye dosya eklenmemiş.',
    GOREV_CAKISMASI: 'Kişinin bu saatlerde başka bir görevi var.',
    IZINLI: 'Kişi bu tarihte izinli.',
    IZIN_GOREV_CAKISMASI: 'Bu tarihlerde kişinin çizelgede görevi var; önce görevi değiştirin.',
    CIZELGE_KILITLI: 'Onaya gönderilmiş veya yayındaki çizelge değiştirilemez.',
    KENDI_CIZELGESI: 'Onaya kendi gönderdiğiniz çizelgeyi onaylayamazsınız.',
    IHLAL_GEREKCESI: 'Çizelgede kural ihlali var; onay için gerekçe yazın.',
    CIZELGE_BOS: 'Boş çizelge onaya gönderilemez.',
    AY_DISI: 'Görev, çizelgenin ayında başlamalı.',
    SUBE_PERSONELI_DEGIL: 'Bu kişinin bu şubede rolü yok.',
  } as Record<string, string>,
};

export type Sozluk = typeof tr;
