/**
 * Arayüz metinleri (Türkçe). Diğer diller (en, ar, ru, de) aynı yapıyla eklenir;
 * `yon: 'rtl'` Arapça için sayfa yönünü çevirir.
 */
export const tr = {
  dil: 'tr',
  yon: 'ltr' as 'ltr' | 'rtl',
  uygulama: {
    ad: 'DC Doktor Klinik',
    aciklama: 'Klinik, poliklinik, diş, estetik, veteriner ve evde sağlık kuruluşları için yönetim platformu',
  },
  genel: {
    devam: 'Devam',
    geri: 'Geri',
    vazgec: 'Vazgeç',
    kaydet: 'Kaydet',
    yukleniyor: 'Yükleniyor…',
    beklenmeyenHata: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
    baglantiHatasi: 'Sunucuya ulaşılamadı. İnternet bağlantınızı kontrol edin.',
    yakinda: 'Yakında',
    tumSubeler: 'Tüm şubeler',
  },
  giris: {
    baslik: 'Giriş yapın',
    altBaslik: 'Kurumunuzun hesabıyla oturum açın.',
    eposta: 'E-posta',
    parola: 'Parola',
    dugme: 'Giriş yap',
    hesabinYokMu: 'Kurumunuz henüz kayıtlı değil mi?',
    kayitOl: 'Kurum kaydı oluşturun',
  },
  kayit: {
    adimlar: ['Kurum tipi', 'Kurum bilgileri', 'Hesabınız', 'Onay'],
    adim: (n: number, toplam: number) => `Adım ${n} / ${toplam}`,
    tip: {
      baslik: 'Kurumunuz hangi hizmetleri veriyor?',
      aciklama:
        'Birden fazla seçebilirsiniz. Seçiminize göre modüller, roller, formlar, zorunlu belgeler ve resmî bağlantılar otomatik hazırlanır. Sonradan şube bazında değiştirilebilir.',
      ozetBaslik: 'Kurumunuz için hazırlanacaklar',
      ozetAlt: 'Seçim değiştikçe güncellenir',
      moduller: 'Modüller',
      roller: 'Roller ve varsayılan yetkiler',
      belgeler: 'Takip edilecek zorunlu belgeler',
      entegrasyonlar: 'Resmî bağlantılar',
      bosSecim: 'Başlamak için en az bir kurum tipi seçin',
      ayriSube:
        'Veteriner hizmeti ile insan sağlığı hizmetleri farklı bakanlıkların mevzuatına tabidir. Bu seçimde sistem her birini ayrı şube olarak açar; hasta ve hayvan kayıtları birbirine karışmaz.',
      secildi: (n: number) => `${n} kurum tipi seçildi`,
    },
    kurum: {
      baslik: 'Kurum bilgileri',
      aciklama: 'Resmî unvan faturalarda ve belgelerde kullanılır.',
      unvan: 'Resmî unvan',
      unvanIpucu: 'Ör. Örnek Sağlık Hizmetleri Ltd. Şti.',
      vergiNo: 'Vergi no veya T.C. kimlik no (isteğe bağlı)',
      subeAdi: 'İlk şubenin adı',
      subeIpucu: 'Ör. Merkez, Kadıköy',
    },
    hesap: {
      baslik: 'Hesabınız',
      aciklama: 'Bu hesap kurumun sahibi olarak açılır. Diğer çalışanları kayıttan sonra davet edersiniz.',
      adSoyad: 'Ad soyad',
      eposta: 'E-posta',
      parola: 'Parola',
      parolaIpucu: 'En az 10 karakter',
      parolaTekrar: 'Parola (tekrar)',
      parolaUyusmuyor: 'Parolalar aynı değil.',
      meslek: 'Mesleğiniz',
      hekimBilgi:
        'Hekim olduğunuz için kurumun mesul müdürü ve hekimi olarak da atanacaksınız. Mesul müdürlüğü sonradan başka bir hekime devredebilirsiniz.',
      idariBilgi:
        'Hekim olmadığınız için hastaların tıbbi kayıtlarını göremezsiniz; işletme verilerini ve anonim istatistikleri görürsünüz. Kayıttan sonra bir hekimi mesul müdür olarak atamanız gerekir.',
    },
    onay: {
      baslik: 'Bilgileri kontrol edin',
      kurumTipleri: 'Kurum tipleri',
      subeler: 'Açılacak şubeler',
      sahip: 'Kurum sahibi',
      kosullar: 'Kullanım koşullarını ve kişisel verilerin işlenmesine ilişkin aydınlatma metnini okudum.',
      kosullarNot: 'Metinler taslaktır; hukuki onay sonrası yayınlanacaktır.',
      dugme: 'Kurumu oluştur',
    },
  },
  panel: {
    menu: {
      komuta: 'Komuta Merkezi',
      randevular: 'Randevular',
      hastalar: 'Hastalar',
      klinik: 'Klinik',
      personel: 'Personel ve Nöbet',
      stok: 'Stok ve Cihaz',
      finans: 'Finans',
      kalite: 'Kalite ve Uyum',
      raporlar: 'Raporlar',
      kullanicilar: 'Kullanıcılar ve Yetkiler',
      denetim: 'Denetim İzi',
      anaMenu: 'Ana menü',
    },
    sube: 'Şube',
    cikis: 'Çıkış yap',
    komuta: {
      baslik: 'Komuta Merkezi',
      hosgeldin: (ad: string) => `Hoş geldiniz, ${ad}`,
      skor: 'Kurum Sağlık Skoru',
      skorBos: 'Randevu, finans ve personel verileri biriktikçe hesaplanır.',
      kurulum: 'Kurulum adımları',
      kurulumAlt: 'Kurumunuzu kullanıma hazırlamak için',
      adimMesul: 'Mesul müdür ata',
      adimMesulTamam: 'Mesul müdür atandı',
      adimEkip: 'Ekibinizi davet edin',
      adimFiyat: 'Hizmet ve fiyat listesini oluşturun',
      adimBelge: 'Ruhsat ve zorunlu belgeleri yükleyin',
      kartlar: {
        randevu: 'Bugünkü randevular',
        ciro: 'Bugünkü ciro',
        alacak: 'Tahsil edilmemiş alacak',
        bekleme: 'Ortalama bekleme',
        veriYok: 'Henüz veri yok',
      },
      yetkisiz: 'Rolünüze ait çalışma ekranları sonraki geliştirme adımlarında açılacak.',
      rolleriniz: 'Rolleriniz',
    },
    kullanicilar: {
      baslik: 'Kullanıcılar ve Yetkiler',
      aciklama: 'Çalışanları ekleyin ve rollerini atayın. Sağlık rollerini mesul müdür onaylar; kimse kendine rol veremez.',
      ekle: 'Kullanıcı ekle',
      eposta: 'E-posta',
      adSoyad: 'Ad soyad',
      meslek: 'Meslek',
      geciciParola: 'Geçici parola',
      geciciParolaIpucu: 'Kişiye güvenli bir yoldan iletin. E-posta ile davet sonraki adımda eklenecek.',
      eklendi: 'Kullanıcı eklendi. Şimdi rolünü atayın.',
      roller: 'Roller',
      rolYok: 'Rol atanmamış',
      rolAta: 'Rol ata',
      rol: 'Rol',
      kapsam: 'Geçerli olduğu yer',
      atandi: 'Rol atandı.',
      kendin: '(siz)',
      rolGerekceleri: {
        'mesul.mudur.ata': 'Mesul müdürü yalnızca kurum sahibi atayabilir.',
        'yetki.saglik.onayla': 'Sağlık rollerini (hekim, hemşire vb.) mesul müdür atar.',
        'kullanici.yonet': 'Bu rolü atamak için kullanıcı yönetimi yetkisi gerekir.',
      } as Record<string, string>,
    },
    denetim: {
      baslik: 'Denetim İzi',
      aciklama: 'Kurumunuzdaki girişler, yetki değişiklikleri ve reddedilen erişimler. Kayıtlar değiştirilemez ve silinemez.',
      zaman: 'Zaman',
      eylem: 'Eylem',
      kullanici: 'Kullanıcı',
      ayrinti: 'Ayrıntı',
      ip: 'IP',
      bos: 'Henüz kayıt yok.',
      eylemler: {
        'kurum.kayit': 'Kurum kaydı oluşturuldu',
        'giris.basarili': 'Giriş yapıldı',
        'giris.basarisiz': 'Başarısız giriş denemesi',
        'kullanici.olusturuldu': 'Kullanıcı eklendi',
        'rol.atandi': 'Rol atandı',
        'rol.atama.reddedildi': 'Rol ataması reddedildi',
        'erisim.reddedildi': 'Yetkisiz erişim denemesi',
      } as Record<string, string>,
    },
  },
  hatalar: {
    GIRIS_BASARISIZ: 'E-posta veya parola hatalı.',
    EPOSTA_KULLANIMDA: 'Bu e-posta adresiyle kayıtlı bir kullanıcı var.',
    KIMLIK_GEREKLI: 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.',
    YETKI_YOK: 'Bu işlem için yetkiniz yok.',
    MESLEK_UYGUN_DEGIL: 'Bu rol, kişinin mesleğine atanamaz.',
    KENDI_YETKISI: 'Kendinize rol atayamazsınız; başka bir yetkili atamalıdır.',
    ROL_ZATEN_ATANMIS: 'Bu rol bu kapsamda zaten atanmış.',
    SUBE_BULUNAMADI: 'Şube bulunamadı.',
    GECERSIZ_ISTEK: 'Bazı alanlar geçersiz.',
  } as Record<string, string>,
};

export type Sozluk = typeof tr;
